#!/bin/sh
set -eu

: "${API_BASE_URL:?API_BASE_URL is required}"
: "${FIREBASE_API_KEY:?FIREBASE_API_KEY is required}"
: "${FIREBASE_AUTH_DOMAIN:?FIREBASE_AUTH_DOMAIN is required}"
: "${FIREBASE_DATABASE_URL:?FIREBASE_DATABASE_URL is required}"
: "${FIREBASE_PROJECT_ID:?FIREBASE_PROJECT_ID is required}"
: "${FIREBASE_STORAGE_BUCKET:?FIREBASE_STORAGE_BUCKET is required}"
: "${FIREBASE_MESSAGING_SENDER_ID:?FIREBASE_MESSAGING_SENDER_ID is required}"
: "${FIREBASE_APP_ID:?FIREBASE_APP_ID is required}"
: "${GOOGLE_CLIENT_ID:?GOOGLE_CLIENT_ID is required}"
: "${GOOGLE_PICKER_API_KEY:?GOOGLE_PICKER_API_KEY is required}"
: "${GOOGLE_SERVICE_ACCOUNT_EMAIL:?GOOGLE_SERVICE_ACCOUNT_EMAIL is required}"

envsubst '${API_BASE_URL} ${FIREBASE_API_KEY} ${FIREBASE_AUTH_DOMAIN} ${FIREBASE_DATABASE_URL} ${FIREBASE_PROJECT_ID} ${FIREBASE_STORAGE_BUCKET} ${FIREBASE_MESSAGING_SENDER_ID} ${FIREBASE_APP_ID} ${GOOGLE_CLIENT_ID} ${GOOGLE_PICKER_API_KEY} ${GOOGLE_SERVICE_ACCOUNT_EMAIL}' \
  < /etc/runtime-config.template.js \
  > /usr/share/nginx/html/assets/runtime-config.js